# Generated by Django 4.2.9 on 2024-02-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_color_colors_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
